### ISSUE TITLE
can't attack if opponent doesnt have card

### ISSUE THREAD

**Issue by Juulis** [mohammedalmahfoodh/group3#42]
multiple solutions....

check in menu if opponent got no cards -> then change menu choice to "attack player"
or
check in attack() if opponent got no cards -> then just don't ask for card to attack, automatic attack player

**Comment by LidiaT80** [comment]
branch attackPlayer har denna funktion, men det verkar inte finnas i dev

**Comment by Juulis** [comment]
> branch attackPlayer har denna funktion, men det verkar inte finnas i dev

Ah! Den var tydligen i dev också.. Men den körs om cardToAttack är null och det är den ju aldrig.. 
Är nog snabbfixat, ska kolla på det nu

**Comment by LidiaT80** [comment]
men kolla i attackPlayer branch i playerMenu

 if (opponentPlayer.getTableCards().isEmpty()){
                    attack(currentPlayer.getTableCards().get(attackCard-1),null);
                }else {
                    attack(currentPlayer.getTableCards().get(attackCard-1),opponentPlayer.getTableCards().get(cardToAttack-1));
                }

**Comment by Juulis** [comment]
> men kolla i attackPlayer branch i playerMenu
> 
> if (opponentPlayer.getTableCards().isEmpty()){
> attack(currentPlayer.getTableCards().get(attackCard-1),null);
> }else {
> attack(currentPlayer.getTableCards().get(attackCard-1),opponentPlayer.getTableCards().get(cardToAttack-1));
> }

Oj jaha, det såg jag inte..
Men det hade inte räckt med menyn ändå, som attack() var nu så slogs ingen tärning för opponent om man attackerade opponent player, och currentPlayer hade inte förlorat hp om man fick mindre på tärningen.

Så jag ändrade lite i if satserna bara så det funkar nu, jag gör en PRQ om 1min så får ni se va ni tycker

EDIT: PRQ uppe nu , det är på samma prq som min förra med attacken som redan ligger uppe.
